#!/bin/bash

# Define the repository owner and name
owner="JNSAPH"
repo="create-furnace-server"
tmp_dir="/tmp/$repo" # Adjusted tmp_dir path

# Use curl to fetch the latest release information from GitHub API
release_info=$(curl -s "https://api.github.com/repos/$owner/$repo/releases/latest")

# Extract the download URL for the .tar.gz file from the JSON response
download_url=$(echo "$release_info" | grep -oP '"browser_download_url": "\K(.*furnace-[0-9.]+\.tar\.gz)"' | head -1 | tr -d '"')

# Extract the latest version from the download URL
get_latest_release() {
    curl --silent "https://api.github.com/repos/JNSAPH/create-furnace-server/releases/latest" |
    grep '"tag_name":' |
    sed -E 's/.*"([^"]+)".*/\1/'
}

latest_version=$(get_latest_release)

# Define the filename
filename="furnace-${latest_version}.tar.gz"

# Welcome message and instructions
echo "
███████╗██╗░░░██╗██████╗░███╗░░██╗░█████╗░░█████╗░███████╗
██╔════╝██║░░░██║██╔══██╗████╗░██║██╔══██╗██╔══██╗██╔════╝
█████╗░░██║░░░██║██████╔╝██╔██╗██║███████║██║░░╚═╝█████╗░░
██╔══╝░░██║░░░██║██╔══██╗██║╚████║██╔══██║██║░░██╗██╔══╝░░
██║░░░░░╚██████╔╝██║░░██║██║░╚███║██║░░██║╚█████╔╝███████╗
╚═╝░░░░░░╚═════╝░╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝░╚════╝░╚══════╝

/ / / / / / / / / / / / / / / / / / / / / / / / / / / / / 

Latest Version: $latest_version

Welcome to the Furnace CLI Installer! This script will download 
the latest version of the Furnace CLI and run it for you. This
might take a few seconds depending on your internet connection.
"


# Create the tmp directory if it doesn't exist
echo "=> Creating tmp directory..."
mkdir -p "$tmp_dir"

# Download the latest release tarball from GitHub
echo "=> Downloading $filename to $tmp_dir..."
curl -s -L "$download_url" -o "$tmp_dir/$filename"
echo "=> Download complete: $filename"

# Unpack the downloaded file into tmp_dir
echo "=> Unpacking $filename into $tmp_dir..."
tar -xf "$tmp_dir/$filename" -C "$tmp_dir"
echo "=> Unpacking complete"

# Execute the furnace script
echo "=> Executing furnace script..."
chmod +x "$current_dir/$tmp_dir/furnace/furnace"
"$current_dir/$tmp_dir/furnace/furnace" < /dev/tty

# Clean up the tmp directory
#rm -rf "$tmp_dir"