name: Furnace CLI Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Release version/name
        required: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Furnace CLI
        run: bun build . --compile --outfile furnace

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: furnace
          path: ./furnace

  release:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Package release
        run: |
          chmod +x furnace
          tar -czvf furnace.tar.gz furnace
          mv furnace.tar.gz furnace-${{ github.event.inputs.version }}.tar.gz

      - name: Display structure of the artifact
        run: ls -R

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with: 
          tag_name: ${{ github.event.inputs.version }}
          generate_release_notes: true
          files: |
            furnace-${{ github.event.inputs.version }}.tar.gz